In [1]:
##Q1
'''Yes, there is a difference in the data type of the variables list_ and array_list. The variable list_ is a Python list,
while array_list is a NumPy array. '''
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_)

print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


In [2]:
##Q2
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_)

# Print data type of each element in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Print data type of each element in array_list
print("Data types of elements in array_list:")
for element in array_list:
    print(type(element))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [3]:
##Q3
'''
Yes, there will be a difference in the data type of the elements present in both list_ and array_list after converting array_list to an array of integers. The elements in list_ will remain strings, while the elements in array_list will be converted to integers.
'''

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_, dtype=int)

for element in list_:
    print(f"datatype of element {element} is: ",type(element))
    
for element in array_list:
    print(f"datatype of array element {element} is: ",type(element))



datatype of element 1 is:  <class 'str'>
datatype of element 2 is:  <class 'str'>
datatype of element 3 is:  <class 'str'>
datatype of element 4 is:  <class 'str'>
datatype of element 5 is:  <class 'str'>
datatype of array element 1 is:  <class 'numpy.int32'>
datatype of array element 2 is:  <class 'numpy.int32'>
datatype of array element 3 is:  <class 'numpy.int32'>
datatype of array element 4 is:  <class 'numpy.int32'>
datatype of array element 5 is:  <class 'numpy.int32'>


In [4]:
#Q4
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

print("shape of array is: ",num_array.shape)
print("size of array is: ",num_array.size)

shape of array is:  (2, 3)
size of array is:  6


In [5]:
#Q5
matrix = np.zeros((3,3))
print(matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
#Q6
matrix = np.eye(5)
print(matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
